[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build:railway"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[deploy]
startCommand = "cd frontend && node server/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3